#!/bin/bash

# Configuration - CHANGE THESE VALUES
PROJECT_ID="gen-lang-client-0314566346"
IMAGE_NAME="bge-m3-service"
REGION="us-central1"
SERVICE_NAME="bge-m3-api"

# API Keys - Replace these with your custom keys
# These keys are custom values that YOU define, not generated by Google
# Clients will need to include one of these keys in their requests
API_KEY_1="your-custom-key-1"
API_KEY_2="your-custom-key-2" 
API_KEY_3="your-custom-key-3"

# Build the Docker image
echo "Building Docker image..."
docker build -t gcr.io/$PROJECT_ID/$IMAGE_NAME .

# Push the image to Google Container Registry
echo "Pushing image to Google Container Registry..."
gcloud auth configure-docker
docker push gcr.io/$PROJECT_ID/$IMAGE_NAME

# Deploy to Cloud Run
echo "Deploying to Cloud Run..."
gcloud run deploy $SERVICE_NAME \
  --image gcr.io/$PROJECT_ID/$IMAGE_NAME \
  --platform managed \
  --region $REGION \
  --memory 4Gi \
  --cpu 2 \
  --timeout 3600 \
  --set-env-vars="ALLOWED_API_KEYS=$API_KEY_1,$API_KEY_2,$API_KEY_3" \
  --no-allow-unauthenticated

echo "Deployment completed! Service URL:"
gcloud run services describe $SERVICE_NAME --platform managed --region $REGION --format 'value(status.url)'

echo ""
echo "==== IMPORTANT: API KEY INFORMATION ===="
echo "You've configured the following API keys:"
echo "1. $API_KEY_1"
echo "2. $API_KEY_2" 
echo "3. $API_KEY_3"
echo ""
echo "Include one of these keys in API requests with the 'X-API-Key' header"
echo "Example: curl -H 'X-API-Key: $API_KEY_1' https://your-service-url/encode"
echo "========================================="
